### PR TITLE
Added URLShortener Python Script

### PR DESCRIPTION
**Pull request by prathimacode-hub**
I've added a python script which shortens the URL. Kindly accept my Pull Request. I have used Pycharm. Thank you.

### CODE REVIEW

**Comment by PrajaktaSathe** [comment]
Good work there! 🙌
Could you please share screenshots of what your code does?

**Comment by prathimacode-hub** [comment]
Yeah, sure. I've added up my screenshot here. 

**Screenshot**

URL Shortener

**Description** 

This project helps in shortening your URL into a customized tiny.url format. Enter your URL in "My URL Shortener" and click an option of "Generate Short URL". It generates the customized URL and displays in the allotted space. You can copy the URL using "Copy URL" button

**Review by PrajaktaSathe — APPROVED** [review]
Great work!

**Comment by prathimacode-hub** [comment]
Thanks for the mention and merging up the PR.

**Pull request merged**
