### PR TITLE
Added Basic Calculator program in GUI

### PR DESCRIPTION
**Pull request by sachinl0har**
Build Using Tkinter Module.

### CODE REVIEW

**Review by PrajaktaSathe — APPROVED** [review]
Good addition!

**Comment by PrajaktaSathe** [comment]
If you could attach a screenshot of the actual calculator, it would be great!

**Comment by sachinl0har** [comment]
Screenshot Added

**Review by PrajaktaSathe — APPROVED** [review]
Great!!
Thanks for contributing!

**Comment by PrajaktaSathe** [comment]
Do star the repo if you find it useful!

**Comment by sachinl0har** [comment]
Sure

**Pull request merged**
