### PR TITLE
ALPHA AI

### PR DESCRIPTION
**Pull request by sachinl0har**
A Basic Virtual Assistant in Python

### CODE REVIEW

**Review by PrajaktaSathe — COMMENTED** [review]
Have you tried running the code? I got some errors in the program. 😅

**Comment by sachinl0har** [comment]
Check now there was an error in Conditional statements
so i solved it now
check if its working or not
Firstly you have to install all the modules that are imported.

**Comment by PrajaktaSathe** [comment]
Could you also attach a screenshot please?

**Comment by sachinl0har** [comment]
Done
its like a talking preprogrammed chatbot in the code i have trigger a sentence i.e., "who are you" then the program will speak the words which you preprogrammed....
you can add more as you want..

**Comment by PrajaktaSathe** [comment]
Great!! Will merge!

**Pull request merged**
