### PR TITLE
added tic-tac-toe.py and updated readme

### PR DESCRIPTION
**Pull request by Kiinitix**

### CODE REVIEW

**Comment by Kiinitix** [comment]
I am extremely sorry about the readme part, give me a second, I'll modify it.

**Review by PrajaktaSathe — CHANGES_REQUESTED** [review]
Good program! Add some documentation to the program.

**Review by PrajaktaSathe — COMMENTED** [review]
If you could add a picture of your program which is running, it would be great!

**Comment by Kiinitix** [comment]
ok

**Comment by Kiinitix** [comment]
Done!

**Review by PrajaktaSathe — APPROVED** [review]

**Pull request merged**
