### PR TITLE
Implemented most of Discussion #15

### PR DESCRIPTION
**Pull request by dalekvim**
I have implemented most of what wanted to do:

Check out the [Online Docs](https://dalekvim.github.io/Python/)! It's not quite complete yet, but it has most of your projects.

The README.rst now has details on how to install dependencies.

I had to make quite a few changes to the code in Acro and Alpha (the chatbots); they had a lot of repeated code and some dependencies that I had trouble installing, but they still have the same features.

### CODE REVIEW

**Comment by PrajaktaSathe** [comment]
Great work until now!!! 💯🙌🏻

**Comment by PrajaktaSathe** [comment]
I would just request a change - https://github.com/Dalekvim/Python/tree/main/projects - You have made folders according to contributors. If possible could you change that and make folders based on some other criteria (or not make folders at all!) it would be great.

**Comment by Dalekvim** [comment]
That won't be a problem, but there are some folders I don't recommend removing:

For example, I've placed the Chatbots together because they were very similar, the files containing the queue for the same reason and the Tkinter projects together because they had GUIs.

Let me know if this is a problem.

**Comment by PrajaktaSathe** [comment]
The way you have combined the chatbots, GUIs, etc. is good. The only issue is the part about the folders made on the basis of the contributors' names. Can you remove that? 
Github_save
The highlighted part in the image is what we could get rid of. We can keep the subfolders.
Will that be possible?

**Comment by sachinl0har** [comment]
@Dalekvim dont give contributers name to the folder.. make it types of projects Like one folder for chatbots other for GUI Apps Like this

**Pull request closed without merging**
