### PR TITLE
Added Rock Paper Scissors Game

### PR DESCRIPTION
**Pull request by Vedant488**
A small addition the list of projects here. Hope you will like it.

### CODE REVIEW

**Review by PrajaktaSathe — APPROVED** [review]
Nice addition to the repo!
Thanks!!
Do star the repo if you find it useful!

**Comment by Vedant488** [comment]
I apologize. The project of mine is not in the project folder as it is supposed to be. If possible please change the location for the file.

**Comment by PrajaktaSathe** [comment]
> I apologize. The project of mine is not in the project folder as it is supposed to be. If possible please change the location for the file.

I did.

**Comment by Vedant488** [comment]
Thank you.

**Pull request merged**
